# Copyright (C) 2019 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/xiaomi/sagit/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/xiaomi/miuicamera/proprietary/vendor/lib/libchromatix_s5k3m3_semco_zsl_preview_ad5816g.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3m3_semco_zsl_preview_ad5816g.so \
    vendor/xiaomi/miuicamera/proprietary/vendor/lib/libchromatix_s5k3m3_semco_zsl_video_ad5816g.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3m3_semco_zsl_video_ad5816g.so \
    vendor/xiaomi/miuicamera/proprietary/vendor/lib/libchromatix_sagit_imx268_liteon_zsl_preview_3a.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_sagit_imx268_liteon_zsl_preview_3a.so \
    vendor/xiaomi/miuicamera/proprietary/vendor/lib/libchromatix_sagit_imx386_semco_4K_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_sagit_imx386_semco_4K_video.so \
    vendor/xiaomi/miuicamera/proprietary/vendor/lib/libchromatix_sagit_imx386_semco_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_sagit_imx386_semco_common.so \
    vendor/xiaomi/miuicamera/proprietary/vendor/lib/libchromatix_sagit_imx386_semco_cpp_hfr_60.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_sagit_imx386_semco_cpp_hfr_60.so \
    vendor/xiaomi/miuicamera/proprietary/vendor/lib/libchromatix_sagit_imx386_semco_cpp_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_sagit_imx386_semco_cpp_hfr_120.so \
    vendor/xiaomi/miuicamera/proprietary/vendor/lib/libchromatix_sagit_imx386_semco_cpp_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_sagit_imx386_semco_cpp_liveshot.so \
    vendor/xiaomi/miuicamera/proprietary/vendor/lib/libchromatix_sagit_imx386_semco_cpp_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_sagit_imx386_semco_cpp_preview.so \
    vendor/xiaomi/miuicamera/proprietary/vendor/lib/libchromatix_sagit_imx386_semco_cpp_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_sagit_imx386_semco_cpp_snapshot.so \
    vendor/xiaomi/miuicamera/proprietary/vendor/lib/libchromatix_imx268_zsl_preview_3a.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx268_zsl_preview_3a.so \
    vendor/xiaomi/miuicamera/proprietary/vendor/lib/libchromatix_sagit_imx386_semco_cpp_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_sagit_imx386_semco_cpp_video.so \
    vendor/xiaomi/miuicamera/proprietary/vendor/lib/libchromatix_sagit_imx386_semco_hfr_60.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_sagit_imx386_semco_hfr_60.so \
    vendor/xiaomi/miuicamera/proprietary/vendor/lib/libchromatix_sagit_imx386_semco_hfr_60_3a.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_sagit_imx386_semco_hfr_60_3a.so \
    vendor/xiaomi/miuicamera/proprietary/vendor/lib/libchromatix_sagit_imx386_semco_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_sagit_imx386_semco_hfr_120.so \
    vendor/xiaomi/miuicamera/proprietary/vendor/lib/libchromatix_sagit_imx386_semco_hfr_120_3a.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_sagit_imx386_semco_hfr_120_3a.so \
    vendor/xiaomi/miuicamera/proprietary/vendor/lib/libchromatix_sagit_imx386_semco_hfr_240_3a.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_sagit_imx386_semco_hfr_240_3a.so \
    vendor/xiaomi/miuicamera/proprietary/vendor/lib/libchromatix_sagit_imx386_semco_postproc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_sagit_imx386_semco_postproc.so \
    vendor/xiaomi/miuicamera/proprietary/vendor/lib/libchromatix_sagit_imx386_semco_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_sagit_imx386_semco_snapshot.so \
    vendor/xiaomi/miuicamera/proprietary/vendor/lib/libchromatix_sagit_imx386_semco_zsl_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_sagit_imx386_semco_zsl_preview.so \
    vendor/xiaomi/miuicamera/proprietary/vendor/lib/libchromatix_sagit_imx386_semco_zsl_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_sagit_imx386_semco_zsl_video.so \
    vendor/xiaomi/miuicamera/proprietary/vendor/lib/libmmcamera_imx268.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_imx268.so \
    vendor/xiaomi/miuicamera/proprietary/vendor/lib/libmmcamera_imx386_semco.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_imx386_semco.so \
    vendor/xiaomi/miuicamera/proprietary/vendor/lib/libmmcamera_s5k3m3_semco.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_s5k3m3_semco.so \
    vendor/xiaomi/miuicamera/proprietary/vendor/lib/libmmcamera_sagit_imx268_liteon.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_sagit_imx268_liteon.so \
    vendor/xiaomi/miuicamera/proprietary/vendor/lib/libmmcamera2_mct.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_mct.so \
	vendor/xiaomi/miuicamera/proprietary/vendor/etc/camera/sagit_imx386_semco_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/sagit_imx386_semco_chromatix.xml 
  



